line_length_guide: 80
soft_tabs: false
theme: Gruvbox
tab_width: 8

types:
  py:
    tab_width: 4
    soft_tabs: true
  md:
    syntax: Markdown
  yml:
    tab_width: 2
    soft_tabs: true
  js:
    tab_width: 4
    soft_tabs: true
  rs:
    tab_width: 4
    soft_tabs: true
  cc:
    tab_width: 4
    soft_tabs: true # looks to be Nix's style
  eml:
    line_length_guide: 72
  COMMIT_EDITMSG:
    line_length_guide: 72
  TAG_EDITMSG:
    line_length_guide: 72
  zig:
    syntax: zig
  nix:
    syntax: Nix
    tab_width: 2
    soft_tabs: true
  y:
    syntax: Yacc
  l:
    syntax: Lex
  html:
    tab_width: 2
    soft_tabs: true

keymap:
  normal:
    s: "cursor::move_down"
    ctrl-s: "cursor::move_to_last_line"
    n: "cursor::move_up"
    ctrl-n: "cursor::move_to_first_line"
    t: "cursor::move_to_start_of_next_token"
    ctrl-t: "cursor::move_right"
    h: "cursor::move_to_start_of_previous_token"
    ctrl-h: "cursor::move_left"
    l: "cursor::move_to_end_of_line"
    r: "cursor::move_to_start_of_line"

    a: "application::switch_to_insert_mode"
    e: "buffer::change_token"
    u: "buffer::save"

    ",": "view::scroll_up"
    ".": "view::scroll_down"
    "'": "buffer::undo"
  select:
    s: "cursor::move_down"
    ctrl-s: "cursor::move_to_last_line"
    n: "cursor::move_up"
    ctrl-n: "cursor::move_to_first_line"
    t: "cursor::move_to_start_of_next_token"
    ctrl-t: "cursor::move_right"
    h: "cursor::move_to_start_of_previous_token"
    ctrl-h: "cursor::move_left"
    l: "cursor::move_to_end_of_line"
    r: "cursor::move_to_end_of_line"
  select_line:
    s: "cursor::move_down"
    ctrl-s: "cursor::move_to_last_line"
    n: "cursor::move_up"
    ctrl-n: "cursor::move_to_first_line"
    t: "cursor::move_to_start_of_next_token"
    ctrl-t: "cursor::move_right"
    h: "cursor::move_to_start_of_previous_token"
    ctrl-h: "cursor::move_left"
    l: "cursor::move_to_end_of_line"
    r: "cursor::move_to_end_of_line"

